-- ============================================================
-- MIGRATION 007: System Alerts
-- ============================================================
-- Stores actionable alerts generated by the daily sync script
-- (e.g. duplicate merchants detected) so the dashboard can
-- surface them to the user for manual resolution.
-- ============================================================

CREATE TABLE system_alerts (
  id           BIGSERIAL PRIMARY KEY,
  type         VARCHAR(50)  NOT NULL,
  severity     VARCHAR(20)  NOT NULL DEFAULT 'warning', -- 'info' | 'warning' | 'error'
  title        VARCHAR(255) NOT NULL,
  details      JSONB,
  resolved     BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  resolved_at  TIMESTAMPTZ
);

CREATE INDEX idx_system_alerts_unresolved ON system_alerts(resolved, created_at DESC);
CREATE INDEX idx_system_alerts_type       ON system_alerts(type);

-- Returns duplicate merchant group/record counts using the canonical
-- normalization function so it stays in sync with the TypeScript code.
CREATE OR REPLACE FUNCTION count_duplicate_merchants()
RETURNS TABLE(duplicate_groups INT, duplicate_records INT)
LANGUAGE SQL AS $$
  WITH renorm AS (
    SELECT
      lower(trim(regexp_replace(regexp_replace(
        translate(lower(name),
          'áàäâãåéèëêíìïîóòöôúùüûñçý',
          'aaaaaaeeeeiiiioooouuuuncy'),
        '[^a-z0-9\s]', '', 'g'),
      '\s+', ' ', 'g'))) AS cn
    FROM merchants
  ),
  groups AS (
    SELECT cn, COUNT(*) AS cnt FROM renorm GROUP BY cn HAVING COUNT(*) > 1
  )
  SELECT
    COUNT(*)::INT                            AS duplicate_groups,
    COALESCE(SUM(cnt) - COUNT(*), 0)::INT   AS duplicate_records
  FROM groups;
$$;
