substitutions:
  _IMAGE: gcr.io/mail-reader-433802/finance-agent-ingestor

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - services/ingestor/Dockerfile
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}
